# Generated by Django 6.1.1 on 2026-09-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationotp',
            name='code',
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='attempts',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='hashed_code',
            field=models.CharField(default=123456, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailverificationotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change')], default='registration', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailverificationotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
