# Generated by Django 6.1.1 on 2026-09-22 12:32
# CHANGE #18 (step 6): adds EmailVerificationOTP.new_email (pending address for EMAIL_CHANGE codes)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emailverificationotp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
