# Generated by Django 6.1.1 on 2026-09-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverificationotp_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationotp',
            name='new_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
