"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

# ===== CHANGE #15: load .env into os.environ.
# The .env file existed with EMAIL_HOST_USER / EMAIL_HOST_PASSWORD, but Django
# does not read .env automatically -- so os.environ.get() below returned None,
# Django skipped SMTP.login() entirely, and Gmail answered
# "530 5.7.0 Authentication Required". load_dotenv() must run BEFORE any
# os.environ.get() in this file. =====
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vlx!n@_den^pwht$h8(%m+vxe64p_!_*)edl0_xo&$f+kugses'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'drf_spectacular',
    'apps.accounts',
    'apps.commons',
    'apps.clinical',
    'apps.inventory',
    'apps.scheduling',
    'apps.notifications',
    'apps.organizations',
    'apps.finance',
    'apps.audit',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
        'OPTIONS' : {
            'host' : 'smtp.gmail.com',
            'port' : 587,
            'use_tls' : True,
            'username' : os.environ.get('EMAIL_HOST_USER'),
            'password' : os.environ.get('EMAIL_HOST_PASSWORD'),  # Replace with your actual email password or use environment variables for security
        }
    },
}
OTP_TTL_MINUTES = 10  # OTP Time-to-Live in minutes
DEFAULT_FROM_EMAIL = 'mir.khamroev@gmail.com'

# Redis configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'


# ===== CHANGE #7 (step 3): rest of the Celery config.
# CELERY_BROKER_URL alone was enough to reach Redis; these pin the serializer and
# make startup resilient. The `CELERY_` prefix matters -- core/celery.py reads
# settings with namespace='CELERY', so un-prefixed names are ignored.
CELERY_RESULT_BACKEND = None   # no result backend on purpose: keeps the plaintext OTP
                               # (passed in the task args) from being persisted after delivery
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# ===== CHANGE #8 (step 4): how many wrong guesses a single OTP tolerates.
# A 6-digit code is only 1,000,000 possibilities, so an unbounded verify endpoint
# is brute-forceable. `attempts` on EmailVerificationOTP is seeded from this and
# counts down; at 0 the code is burned (is_used=True).
OTP_MAX_ATTEMPTS = 5

# ===== CHANGE #13 (step 5): brand name used in email subjects and templates.
SITE_NAME = 'MediFlow ERP'
