# Generated by Django 6.1.1 on 2026-10-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='user_name',
            new_name='username',
        ),
    ]
